<?php

namespace Sistema\ClienteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClienteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sistema\ClienteBundle\Controller\ClienteController();
        return $instance;
    }
}
