<?php

namespace Sistema\PaqueteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteRepository extends EntityRepository
{
    public function findPaqueteDelDia()
    {
        $fechaHoy = new \DateTime('today');
        $fechaHoy->setTime(23, 59, 59);
        
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT p FROM PaqueteBundle:Paquete p
                                       WHERE p.creado <= :fecha
                                       ORDER BY p.actualizado DESC');
        
        $consulta->setMaxResults(3);
        $consulta->setParameter('fecha', $fechaHoy);
        
        return $consulta->getResult();
    }
    public function total() 
    {
        $em = $this->getEntityManager();
        
        $total = $this->getPrecio()->getPaquete();
    }
}
