<?php

namespace Sistema\PaqueteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaRepository extends EntityRepository
{
    public function findUltimasVentas()
    {
        $fechaHoy = new \DateTime('today');
        $fechaHoy->setTime(23, 59, 59);
        
        return $this->getEntityManager()->createQuery('
            SELECT v, p 
            FROM PaqueteBundle:Venta v
            JOIN v.paquete p
            WHERE v.fecha <= :fHoy
            ORDER BY v.fecha DESC')
        
        ->setMaxResults(3)
        ->setParameter('fHoy', $fechaHoy)
        ->getResult();
    }
    
    public function cuentaVentas()
    {
        //select count(*) as c from ventas
        return $this->getEntityManager()->createQuery('
            SELECT COUNT (v)
            FROM PaqueteBundle:Venta v')
                            
        ->getSingleScalarResult();

    }
    
    public function totalVentas($offset, $porpagina)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT v.id, v.fecha, v.total, c.nombrec, c.apellidoc, p.slug, u.apellido, u.nombre
             FROM PaqueteBundle:Venta v, ClienteBundle:Cliente c, UsuarioBundle:Usuario u, PaqueteBundle:Paquete p
             WHERE v.cliente=c.id AND v.usuario=u.id AND v.paquete=p.id
             ORDER BY v.id DESC')

        ->setFirstResult($offset)
        ->setMaxResults($porpagina)
        ->getResult();         
    }
}
