#cliente_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ClienteBundle:Default:index }
    
#cliente_new:
#    pattern:  /new
#    defaults: { _controller: ClienteBundle:Cliente:new }    
