<?php

namespace Sistema\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    public function findClienteMayor()
    {
        $em = $this->getDoctrine()->getEntityManager();
        $consulta = $em->createQuery('SELECT c FROM ClienteBundle:Cliente c WHERE
                                        c.nombre = :nombre');
        $consulta->setParameter('nombre', juan);
        $consulta->getResult();
    }
}
